apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggingservice-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggingservice-master
  template:
    metadata:
      labels:
        app: loggingservice-master
    spec:
      containers:
      - name: loggingservice-master
        image: tusharcontainer.azurecr.io/singh-aakash/loggingservice:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: aksushar
---
apiVersion: v1
kind: Service
metadata:
  name: loggingservice-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: loggingservice-master
